kind: pipeline
type: docker
name: build

steps:
- name: build
  image: "node:alpine"
  commands:
  - yarn
  - yarn build

kind: pipeline
type: docker
name: deploy

steps:
- name: copyfiles
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: HOST
    port: 22
    key:
      from_secret: SSH_KEY
    source: dist
    target: ~/apps/redux
    username:
      from_secret: USER

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: HOST
    port: 22
    key:
      from_secret: SSH_KEY
    username:
      from_secret: USER
    script: bash ~/apps/portfolio/deploy.sh

trigger:
  branch: 
  - master
  event: 
  - push

